### ISSUE TITLE
Property 'books' has no initializer and is not definitely assigned in the constructor

### ISSUE THREAD

**Issue by georgiossalonad** [book-monkey4/iteration-1-components#4]
Ich habe das Buch bis Seite 99 gelesen und den Code so übernommen wie der ist.

Leider bekomme ich eine Fehlermeldung im `book-list.component.ts`

**Comment by fmalcher** [comment]
Danke für deine Nachricht. Welche Auflage des Buchs besitzt du?

**Comment by fmalcher** [comment]
Der Code aus diesem Repo funktioniert bei mir ohne Probleme. Vergleich doch am besten nochmal deine Implementierung mit diesem Code. 🙂

**Comment by fmalcher** [comment]
Falls das nichts bringt, gib uns bitte ein paar mehr Infos:
- Welche IDE nutzt du?
- Baut das Projekt trotzdem?
- Ist es eine Fehlermeldung oder Warnung? Wo siehst du die Meldung?
- Woher kommt die Meldung? (z.B. tslint)

**Comment by georgiossalonad** [comment]
Ich besitze die 3. Auflage und benutze VSCode.

Wenn ich `ng serve` im Terminal eingebe bekomme ich die folgende Fehlermeldung:

`Error: src/app/book-list/book-list.component.ts:11:3 - error TS2564: Property 'books' has no initializer and is not definitely assigned in the constructor.`

Im Browser bekomme ich das folgende: Cannot GET /

Dazu noch der Code 

```
import { Component, OnInit } from '@angular/core';

import { Book } from '../shared/book';

@Component({
  selector: 'bm-book-list',
  templateUrl: './book-list.component.html',
  styleUrls: ['./book-list.component.css']
})
export class BookListComponent implements OnInit {
  books: Book[];

  ngOnInit(): void {
    this.books = [
      {
        isbn: '9783864907791',
        title: 'Angular',
        authors: ['Ferdinand Malcher', 'Johannes Hoppe', 'Danny Koppenhagen'],
        published: new Date(2020, 8, 1),
        subtitle: 'Grundlagen, fortgeschrittene Themen und Best Practices',
        rating: 5,
        thumbnails: [{
          url: 'https://ng-buch.de/angular-cover.jpg',
          title: 'Buchcover'
        }],
        description: 'Lernen Sie Angular mit diesem Praxisbuch!'
      },
      {
        isbn: '9783864905520',
        title: 'React',
        authors: ['Oliver Zeigermann', 'Nils Hartmann'],
        published: new Date(2019, 11, 12),
        subtitle: 'Grundlagen, fortgeschrittene Techniken und Praxistipps',
        rating: 3,
        thumbnails: [{
          url: 'https://ng-buch.de/react-cover.jpg',
          title: 'Buchcover'
        }],
        description: 'Das bewährte und umfassende Praxisbuch zu React.'
      }
    ];
  }
}

```

<img width="450" alt="Bildschirmfoto 2021-02-11 um 11 16 35" src="https://user-images.githubusercontent.com/78490462/107624097-aa99e180-6c5a-11eb-8a86-54c420378915.png">

**Comment by fmalcher** [comment]
Kannst Du Dein Projekt bitte einmal in ein GitHub-Repo pushen? Dann gucke ich mir das kurz an.

**Comment by fmalcher** [comment]
Noch eine Idee: Schau mal bitte in deine `tsconfig.json` und `tsconfig.app.json` nach dieser Einstellung:

```
"strictPropertyInitialization": false
```

Wenn Du den Wert auf `false` setzt, dürfte es funktionieren.
Alternativ kannst Du das Property auch direkt initialisieren (`books: Book[] = []`).
Wir haben den Strict Mode im Buch nicht aktiviert, daher ist der "Fehler" dort nicht aufgefallen.

**Comment by georgiossalonad** [comment]
Repo: https://github.com/georgiossalonad/book-monkey

Die Einstellung `strictPropertyInitialization`gibt es bei mir nirgendswo zu finden.

Klar das `books: Book[] = []` behebt den Fehler. Ich wollte aber wissen, warum ich die Fehlermeldung bekomment habe.

**Comment by fmalcher** [comment]
Dann füg die Einstellung mal bitte in die tsconfig.json ein (mit false) 🙂
